#!/bin/bash

mysqladmin -u root drop wordpress
mysqladmin -u root create wordpress

mysql -u root wordpress < backup-hostname-date-wordpress.sql

# reset workpress user's password in mysql and 
# mysql -u root -h localhost
# ALTER USER 'wordpress'@'localhost' IDENTIFIED BY 'New-Password-Here';
# EXIT

# Edit /var/www/html/wp-config.php to use the new database password
# /** MySQL database password */
# define( 'DB_PASSWORD', 'New-Password-Here' );

sudo tar -xzvf backup-hostname-date-www.tgz -C /
