---
# To install WordPress on CentOS 7 cloud server
#
# Needs passwords from a vault, so make the vault with:
#   ansible-vault create secret.yml
# Encrypt the SSL files with ansible-vault using the same password:
#   ansible-vault encrypt site.key site.crt site.ca-bundle
# Run with something like:
#   ansible-playbook wordpress_playbook.yaml --ask-vault-pass

- hosts: all
  remote_user: centos
  become: yes
  vars: 
    swap_file_path: '/swapfile'
    ssl_filename_heading: 'scrambled_xyz'
    website_domain_name: 'scrambled.xyz'
  
  # Store passwords in the file secret.yml:
  # wordpress_database_user_password: password-here
  vars_files:
    - "secret.yml"
  
  tasks:

    # Add a swap file so Yum / MariaDB can run on a low RAM machine.
    - name: Create swap file
      command: dd if=/dev/zero of={{ swap_file_path }} bs=1024 count=4M
               creates="{{ swap_file_path }}"
      tags:
        - swap.file.create

    - name: Set swap file permissions
      file: path="{{ swap_file_path }}"
            owner=root
            group=root
            mode=0600
      tags:
        - swap.file.permissions

    - name: Check if swap space exists
      command: file {{ swap_file_path }}
      register: swapfile
      tags:
        - swap.file.mkswap

    - name: Make swap space if needed
      command: "mkswap {{ swap_file_path }}"
      when: swapfile.stdout.find('swap file') == -1
      tags:
        - swap.file.mkswap

    - name: Write swap entry in fstab
      mount: name=none
             src={{ swap_file_path }}
             fstype=swap
             opts=sw
             passno=0
             dump=0
             state=present
      tags:
        - swap.fstab

    - name: If there is no swap space, turn it on
      command: "swapon {{ swap_file_path }}"
      when: ansible_swaptotal_mb < 1
      tags:
        - swap.file.swapon


    - name: Upgrade all packages
      yum:
       name: '*'
       state: latest

    - name: Install httpd packages
      yum:
       name: 
        - httpd
        - mod_ssl
       state: latest

    - name: Copy domain certificate file
      copy:
        src: "./{{ ssl_filename_heading }}.crt"
        dest: "/etc/pki/tls/certs/"
        backup: yes
        group: root
        owner: root
        mode: u+rw,g=,o=

    - name: Copy certificate authority bundle file
      copy:
        src: "./{{ ssl_filename_heading }}.ca-bundle"
        dest: "/etc/pki/tls/certs/"
        backup: yes
        group: root
        owner: root
        mode: u+rw,g=,o=
        
    - name: Copy private key file
      copy:
        src: "./{{ ssl_filename_heading }}.key"
        dest: "/etc/pki/tls/private/"
        backup: yes
        group: root
        owner: root
        mode: u+rw,g=,o=

# edit conf.file
# add
# redirect to https
# Redirect / https://secure.example.com/
# Redirect permanent / https://secure.example.com/

    - name: Set the web site's domain name
      lineinfile:
        path: /etc/httpd/conf.d/ssl.conf
        regexp: '^#?ServerName .*$'
        line:  'ServerName {{ website_domain_name }}:443'
        backup: yes
        
    - name: Disable weak SSL Protocols
      lineinfile:
        path: /etc/httpd/conf.d/ssl.conf
        regexp: '^SSLProtocol .*$'
        line:  'SSLProtocol all -SSLv2 -SSLv3 -TLSv1 -TLSv1.1'
        backup: yes

    - name: Disable weak SSL Cipher Suites
      lineinfile:
        path: /etc/httpd/conf.d/ssl.conf
        regexp: '^SSLCipherSuite .*$'
        line:  'SSLCipherSuite HIGH:!MD5:!MEDIUM:!LOW'
        backup: yes
        
    - name: Disable SSL Compression
      lineinfile:
        path: /etc/httpd/conf.d/ssl.conf
        insertbefore: '^\s*<VirtualHost _default_:443>'
        line:  'SSLCompression off'
        backup: yes
        
    - name: Disable SSL SessionTickets
      lineinfile:
        path: /etc/httpd/conf.d/ssl.conf
        insertbefore: '^\s*SSLCompression off'
        line:  'SSLSessionTickets off'
        backup: yes
    
    - name: Install the SSL certificate
      lineinfile:
        path: /etc/httpd/conf.d/ssl.conf
        regexp: '^#?\s*SSLCertificateFile .*$'
        line:  'SSLCertificateFile /etc/pki/tls/certs/{{ ssl_filename_heading }}.crt'
        backup: yes
        
    - name: Install the SSL certificate authority certificate chain
      lineinfile:
        path: /etc/httpd/conf.d/ssl.conf
        regexp: '^#?\s*SSLCACertificateFile .*$'
        line:  'SSLCACertificateFile /etc/pki/tls/certs/{{ ssl_filename_heading }}.ca-bundle'
        backup: yes
        
    - name: Install the SSL certificate private key
      lineinfile:
        path: /etc/httpd/conf.d/ssl.conf
        regexp: '^SSLCertificateKeyFile .*$'
        line:  'SSLCertificateKeyFile /etc/pki/tls/private/{{ ssl_filename_heading }}.key'
        backup: yes

    - name: Set the hostname
      command: hostnamectl set-hostname {{ website_domain_name }}
    
    - name: Enable and start httpd service
      service:
       name: httpd
       enabled: yes
       state: started

    - name: Install epel-release package
      yum:
       name: epel-release
       state: latest

    - name: Install utility packages
      yum:
       name:
        - nano
        - mc
        - wget
        - net-tools
        - unzip
        - fail2ban
        - yum-cron
        - yum-utils
        - aide
        - haveged
       state: latest

    - name: Enable and start the haveged service for better entropy
      service:
       name: haveged
       enabled: yes
       state: started
       
    - name: Enable MariaDB repository
      yum_repository:
        name: MariaDB
        description: MariaDB repository for CentOS 7
        baseurl: https://yum.mariadb.org/10.3/centos7-amd64
        enabled: yes
        gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
        gpgcheck: yes
        
    - name: Install MariaDB / MySQL database packages
      yum:
       name:
        - MariaDB-server
        - MariaDB-client
        - MySQL-python
       state: latest

    - name: Enable and start MariaDB service
      service:
       name: mariadb
       enabled: yes
       state: started
    
    - name: Install Remi's PHP repository package
      yum:
       name: https://rpms.remirepo.net/enterprise/remi-release-7.rpm
       state: latest
       
    - name: Enable Remi's PHP repository
      yum_repository:
        name: remi-php73
        description: Remi's PHP 7.3 RPM repository for CentOS $releasever
        mirrorlist: https://rpms.remirepo.net/enterprise/7.4/php73/mirror
        enabled: yes
        gpgcheck: yes
        gpgkey: https://rpms.remirepo.net/RPM-GPG-KEY-remi

    # https://make.wordpress.org/hosting/handbook/handbook/server-environment/#php-extensions
    - name: Install PHP packages
      yum:
        name:
          - php
          - php-mysql
          - php-bcmath
          - php-imagick
          - php-xml
          - php-xmlrpc
          - php-json
          - php-mbstring
          - php-ssh2
          - php-posix
        state: latest

    - name: Restart the httpd service to enable PHP
      service:
       name: httpd
       state: restarted

#    - name: Set the MySql root user's password
#      command: mysqladmin -u root password ""
# needs to include the db user password for future runs

    # mysql -u root
    # mysql> CREATE DATABASE wordpress;
    - name: Create a database for WordPress
      mysql_db:
        name: wordpress
        state: present

    # mysql> CREATE USER 'wordpress'@'localhost' IDENTIFIED BY 'password';
    # mysql> GRANT ALL PRIVILEGES ON wordpress.* TO 'wordpress'@'localhost';
    # mysql> FLUSH PRIVILEGES;

    - name: Create user and set password for WordPress to login to database with
      mysql_user:
        name: wordpress
        state: present
        priv: wordpress.*:ALL
        password: "{{ wordpress_database_user_password }}"

#   Need to do the equivalent of run mysql_secure_installation 


    - name: Download and extract the WordPress installation archive
      unarchive:
        src: https://wordpress.org/latest.tar.gz
        dest: ~/
        remote_src: yes
        creates: ~/wordpress
        
    - name: Copy WordPress files to the web site root folder
      command: cp -r ~/wordpress/. /var/www/html
      args:
        creates: /var/www/html/wp-settings.php


    # change the file owner and permissions for the WordPress files
    - name: Give "apache" permissions to the WordPress folder
      file:
        path: /var/www/html
        owner: apache
        group: apache
        mode: 0755
        recurse: yes
      tags: apache-permissions
        
    # Tell SElinux to allow writes for WP install
    # semanage fcontext -a -t httpd_sys_rw_content_t "/var/www/html(/.*)?" 
    # sudo restorecon -R -v /var/www/html/
    # /var/www/html/uploads
    - name: Allow httpd to modify WordPress files for updates
      sefcontext:
        target: '/var/www/html(/.*)?'
        setype: httpd_sys_rw_content_t
        state: present
      tags: apache-permissions

    - name: Apply SELinux file context
      command: restorecon -i -R /var/www/html
      tags: apache-permissions

    - name: Enable and start the firewall service
      service:
       name: firewalld
       enabled: yes
       state: started
       
    - name: Allow HTTP through the local firewall
      firewalld:
        service: http
        permanent: yes
        immediate: yes
        state: enabled

    - name: Allow HTTPS through the local firewall
      firewalld:
        service: https
        permanent: yes
        immediate: yes
        state: enabled

# restore mysql database?

...

