---

ssl_filename_heading: 'scrambled_xyz'
website_domain_name: 'scrambled.xyz'
swap_file_path: '/swapfile'
email_to: 'user@example.com'

# Store the database password in the file secret.yml in this format:
# 
# wordpress_database_user_password: password-goes-here

...