---

ssl_filename_heading: 'example_com'
website_domain_name: 'example.com'
email_to: 'user@example.com'

swap_file_path: '/swapfile'

# Store the database password in the file secret.yml in this format:
# 
# wordpress_database_user_password: password-goes-here

...